# Generated by Django 2.1.3 on 2018-11-06 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fantasyFootball.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a_goals', models.SmallIntegerField()),
                ('team_b_goals', models.SmallIntegerField()),
                ('match_date', models.DateTimeField(verbose_name='date of match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('player_surname', models.CharField(max_length=30)),
                ('player_picture', models.FileField(default='', upload_to=fantasyFootball.models.player_pic_path)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.FileField(default='', upload_to=fantasyFootball.models.user_avatar_path)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium_name', models.CharField(max_length=50)),
                ('stadium_image', models.FileField(default='', upload_to=fantasyFootball.models.stadium_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('foundation_date', models.DateTimeField(verbose_name='date Founded')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('team_logo', models.FileField(default='', upload_to=fantasyFootball.models.team_logo_path)),
            ],
        ),
        migrations.AddField(
            model_name='stadium',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasyFootball.Team'),
        ),
        migrations.AddField(
            model_name='profile',
            name='manage_teams',
            field=models.ManyToManyField(to='fantasyFootball.Team'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasyFootball.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasyFootball.Stadium'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='fantasyFootball.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='fantasyFootball.Team'),
        ),
    ]
