# Generated by Django 2.1.3 on 2018-11-08 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fantasyFootball.models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyFootball', '0002_auto_20181108_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_position',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_picture',
            field=models.FileField(blank=True, default='', upload_to=fantasyFootball.models.player_pic_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_avatar',
            field=models.FileField(blank=True, default='', upload_to=fantasyFootball.models.user_avatar_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
