# Generated by Django 2.1.3 on 2018-11-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyFootball', '0003_auto_20181108_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to='fantasyFootball.Team'),
        ),
    ]
